"use client"; // Add this line at the top

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  const showLayout = pathname !== '/login';

  return (
    <html lang="en">
      <body className={inter.className}>
        {showLayout && <Header />}
        {showLayout && <Sidebar />}
        {children}
      </body>
    </html>
  )
}
